### ISSUE TITLE
cannot override local variables

### ISSUE THREAD

**Issue by tasiotas** [inkline/nuxt-module-inkline#9]
Hi,

I cannot seem to be able to configure local variables.

I use new option `sassVariables`:

nuxt.config.ts
```js
inkline: {
    css: true,
    sassVariables: ['~/assets/css/main.scss'],
  },
```

main.scss
```css
@import '@inkline/inkline/css/variables';
@import '@inkline/inkline/css/mixins';

@include i-button() {
  ----border-width: 10px;
}
```

But still no luck. Here is repro on StackBlitz
https://stackblitz.com/edit/nuxt-starter-st6ssq?file=assets/css/main.scss
